#include <uti/category.h>
#include <uti/stntype.h>
CCATEGORY STNTYPE All_PASS_0;
CCATEGORY STNTYPE HW_OS_FAIL_0;
CCATEGORY STNTYPE HW_UID_TEST_FAIL_0;
CCATEGORY STNTYPE HW_ENABLE_Voltage_FAIL_0;
CCATEGORY STNTYPE HW_SWD_RESET_FAIL_0;
CCATEGORY STNTYPE HW_POWER_SWICTH_FAIL_0;
CCATEGORY STNTYPE HW_Fail_last_item_test_0;
CCATEGORY STNTYPE SYS_ERROR_HW_BIN_0;
CCATEGORY STNTYPE All_PASS_1;
CCATEGORY STNTYPE SW_OS_FAIL_1;
CCATEGORY STNTYPE SW_RESET_SWD_FAIL_1;
CCATEGORY STNTYPE SW_UID_TEST_FAIL_1;
CCATEGORY STNTYPE SW_ENABLE_Voltage_FAIL_1;
CCATEGORY STNTYPE SW_SWD_RESET_FAIL_1;
CCATEGORY STNTYPE SW_POWER_SWICTH_FAIL_1;
CCATEGORY STNTYPE SW_Fail_last_item_test_1;
CCATEGORY STNTYPE SYS_ERROR_SW_BIN_1;
