#include <uti/clabel.h>
#include <uti/stntype.h>
CLABEL STNTYPE GET_CHIP_ID;
CLABEL STNTYPE __GET_CHIP_ID;
CLABEL STNTYPE Reset_SWD;
CLABEL STNTYPE __Reset_SWD;
CLABEL STNTYPE wstart_data;
CLABEL STNTYPE wstart_head;
CLABEL STNTYPE WIRTE_WORD;
CLABEL STNTYPE __WIRTE_WORD;
CLABEL STNTYPE Capture_addr;
CLABEL STNTYPE CAPTURE_WORD;
CLABEL STNTYPE __CAPTURE_WORD;
CLABEL STNTYPE wread_data;
CLABEL STNTYPE wread_addr;
CLABEL STNTYPE READ_WORD;
CLABEL STNTYPE __READ_WORD;
