#include <uti/category.h>
#define __CLASS_BODY__
#include <uti/stntype.h>
CCATEGORY STNTYPE All_PASS_0("All_PASS",0);
CCATEGORY STNTYPE HW_OS_FAIL_0("HW_OS_FAIL",0);
CCATEGORY STNTYPE HW_UID_TEST_FAIL_0("HW_UID_TEST_FAIL",0);
CCATEGORY STNTYPE HW_ENABLE_Voltage_FAIL_0("HW_ENABLE_Voltage_FAIL",0);
CCATEGORY STNTYPE HW_SWD_RESET_FAIL_0("HW_SWD_RESET_FAIL",0);
CCATEGORY STNTYPE HW_POWER_SWICTH_FAIL_0("HW_POWER_SWICTH_FAIL",0);
CCATEGORY STNTYPE HW_SPLINE_FAIL_0("HW_SPLINE_FAIL",0);
CCATEGORY STNTYPE HW_Fail_last_item_test_0("HW_Fail_last_item_test",0);
CCATEGORY STNTYPE SYS_ERROR_HW_BIN_0("SYS_ERROR_HW_BIN",0);
CCATEGORY STNTYPE All_PASS_1("All_PASS",1);
CCATEGORY STNTYPE SW_OS_FAIL_1("SW_OS_FAIL",1);
CCATEGORY STNTYPE SW_RESET_SWD_FAIL_1("SW_RESET_SWD_FAIL",1);
CCATEGORY STNTYPE SW_UID_TEST_FAIL_1("SW_UID_TEST_FAIL",1);
CCATEGORY STNTYPE SW_ENABLE_Voltage_FAIL_1("SW_ENABLE_Voltage_FAIL",1);
CCATEGORY STNTYPE SW_SWD_RESET_FAIL_1("SW_SWD_RESET_FAIL",1);
CCATEGORY STNTYPE SW_POWER_SWICTH_FAIL_1("SW_POWER_SWICTH_FAIL",1);
CCATEGORY STNTYPE SW_SPLINE_FAIL_1("SW_SPLINE_FAIL",1);
CCATEGORY STNTYPE SW_LDO18_TRIM_FAIL_1("SW_LDO18_TRIM_FAIL",1);
CCATEGORY STNTYPE SW_RCL_TRIM_FAIL_1("SW_RCL_TRIM_FAIL",1);
CCATEGORY STNTYPE SW_VERSION_FAIL_1("SW_VERSION_FAIL",1);
CCATEGORY STNTYPE SW_Fail_last_item_test_1("SW_Fail_last_item_test",1);
CCATEGORY STNTYPE SYS_ERROR_SW_BIN_1("SYS_ERROR_SW_BIN",1);
